VIA_ENABLE = no
ENCODER_MAP_ENABLE = yes
TRI_LAYER_ENABLE = yes
COMBO_ENABLE = yes
KEY_LOCK_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
LTO_ENABLE = yes
OS_DETECTION_ENABLE = yes
LEADER_ENABLE = yes
REPEAT_KEY_ENABLE = yes

ifeq ($(strip $(RGB_MATRIX_ENABLE)), yes)
    SRC += rgb_matrix_user.c
endif
